package com.example.learnlog.data.model

import java.util.Date

enum class StudyType {
    CLASS,
    EXAM_PREP,
    ASSIGNMENT_WORK,
    PERSONAL_STUDY
}

enum class SessionStatus {
    PENDING,
    IN_PROGRESS,
    COMPLETED,
    SKIPPED
}

data class StudySession(
    val id: Long = 0,
    val title: String,
    val subject: String,
    val startTime: Date,
    val duration: Int, // in minutes
    val type: StudyType,
    val status: SessionStatus = SessionStatus.PENDING,
    val relatedTaskId: Long? = null, // Reference to associated task if any
    val isAutoGenerated: Boolean = false,
    val completedDuration: Int = 0, // actual time spent
    val notes: String = ""
)

data class TimeSlot(
    val startTime: Date,
    val endTime: Date,
    val isAvailable: Boolean = true
)
