package com.example.learnlog.data.model

import org.threeten.bp.LocalDateTime

enum class SessionStatus {
    PENDING,
    IN_PROGRESS,
    COMPLETED,
    SKIPPED
}

data class StudySession(
    val id: Long,
    val title: String,
    val subject: String,
    val startTime: LocalDateTime,
    val endTime: LocalDateTime,
    val durationMinutes: Int,
    val type: StudyType,
    val status: SessionStatus = SessionStatus.PENDING,
    val relatedTaskId: Long? = null,
    val isAutoGenerated: Boolean = false
)

data class TimeSlot(
    val startTime: LocalDateTime,
    val endTime: LocalDateTime,
    val isAvailable: Boolean = true
)
